import { VersionParameterNames } from './parameterNames';

export const globalDataAttributeMapper: Record<VersionParameterNames, string> = {
  [VersionParameterNames.version]: 'version',
  [VersionParameterNames.extrusion]: 'extrusion',
  [VersionParameterNames.extrusionType]: 'type',
  [VersionParameterNames.radiusTop]: 'radiusTop',
  [VersionParameterNames.insetTop]: 'insetTop',
  [VersionParameterNames.insetBottom]: 'insetBottom',
  [VersionParameterNames.insetSides]: 'insetSides',
  [VersionParameterNames.footprint]: 'footprint',
  [VersionParameterNames.footprintType]: 'type',
  [VersionParameterNames.size]: 'size',
  [VersionParameterNames.xCount]: 'xCount',
  [VersionParameterNames.yCount]: 'yCount',
  [VersionParameterNames.bufferInside]: 'bufferInside',
  [VersionParameterNames.radius0]: 'radius0',
  [VersionParameterNames.radius1]: 'radius1',
  [VersionParameterNames.radius2]: 'radius2',
  [VersionParameterNames.bufferOutside]: 'bufferOutside',
  [VersionParameterNames.segments]: 'segments',
  [VersionParameterNames.circleRadius]: 'circleRadius',
  [VersionParameterNames.circleDivisions]: 'circleDivisions',
  [VersionParameterNames.angleSplit]: 'angleSplit',
  [VersionParameterNames.offsetA]: 'offsetA',
  [VersionParameterNames.offsetB]: 'offsetB',
  [VersionParameterNames.innerRadius]: 'innerRadius',
  [VersionParameterNames.heights]: 'heights',
  [VersionParameterNames.heightProcessingMethod]: 'method',
  [VersionParameterNames.baseHeight]: 'baseHeight',
  [VersionParameterNames.storyCount]: 'storyCount',
  [VersionParameterNames.processingMethodType]: 'type',
  [VersionParameterNames.total]: 'total',
  [VersionParameterNames.linearTwist]: 'angle',
  [VersionParameterNames.maxAmplitude]: 'max',
  [VersionParameterNames.minAmplitude]: 'min',
  [VersionParameterNames.period]: 'period',
  [VersionParameterNames.phaseShift]: 'phaseShift',
};
